### ISSUE TITLE
Need help from Yotam Mann

### ISSUE THREAD

**Issue by KarrascoJena** [Tonejs/Midi#91]
Hi Yotam.
I have to use your Tonejs/Midi module. So I have tried to check the example. But not working.
There is an error on the console like this
![image](https://user-images.githubusercontent.com/54128071/71086724-8452f000-21d5-11ea-80fc-b12135f63faa.png)

So I ignore the example and followed your guide.
But has an error related to "await"
![image](https://user-images.githubusercontent.com/54128071/71086944-017e6500-21d6-11ea-8916-b6233eb2fad3.png)

So I ignored the await as well.
In that case, got the console error "Cannot read property 'formUrl' of undefined"
![image](https://user-images.githubusercontent.com/54128071/71087194-8e292300-21d6-11ea-9a92-6a6cfc5b36c2.png)

I don't know what I have wrong. So there is another option or need pre-work for that?
Please help me.
Also, the guide is lack for me, I think. So If you have another guide which in more detail.  it will help me.

**Comment by tambien** [comment]
i think the first issue might be because you are trying to load the file without having a server running. I see the requested URL starts with `file://`. Try using an http url and running an [http-server](https://www.npmjs.com/package/http-server)
